
#include "schema/tpcc.h"

const char *default_tpcc = "\n"
                           "table {\n"
                           "  name=\"warehouse\"\n"
                           "  rows=S\n"
                           "\n"
                           "  column { name=\"w_id\"; type=smallint; primary key; pool=S*2 }\n"
                           "  column { name=\"w_name\"; type=varchar(10) }\n"
                           "  column { name=\"w_street_1\"; type=varchar(20) }\n"
                           "  column { name=\"w_street_2\"; type=varchar(20) }\n"
                           "  column { name=\"w_city\"; type=varchar(20) }\n"
                           "  column { name=\"w_state\"; type=char(2); pool=50 }\n"
                           "  column { name=\"w_zip\"; type=char(9); pool=41000 }\n"
                           "  column { name=\"w_tax\"; type=real }\n"
                           "  column { name=\"w_ytd\"; type=float }\n"
                           "}\n"
                           "\n"
                           "table {\n"
                           "  name=\"district\"\n"
                           "  rows=S*10\n"
                           "\n"
                           "  column { name=\"d_id\"; type=smallint; primary key; pool=20 }\n"
                           "  column { name=\"d_w_id\"; type=smallint; primary key }\n"
                           "  column { name=\"d_name\"; type=varchar(10) }\n"
                           "  column { name=\"d_street_1\"; type=varchar(20) }\n"
                           "  column { name=\"d_street_2\"; type=varchar(20) }\n"
                           "  column { name=\"d_city\"; type=varchar(20) }\n"
                           "  column { name=\"d_state\"; type=char(2); pool=&warehouse.w_state }\n"
                           "  column { name=\"d_zip\"; type=char(9); pool=&warehouse.w_zip }\n"
                           "  column { name=\"d_tax\"; type=real }\n"
                           "  column { name=\"d_ytd\"; type=float }\n"
                           "  column { name=\"d_next_o_id\"; type=int }\n"
                           "\n"
                           "  foreign key d_w_id => warehouse(w_id)\n"
                           "}\n"
                           "\n"
                           "table {\n"
                           "  name=\"customer\"\n"
                           "  rows=S*30000\n"
                           "\n"
                           "  column { name=\"c_id\"; type=int; primary key; pool=96000 }\n"
                           "  column { name=\"c_d_id\"; type=smallint; primary key }\n"
                           "  column { name=\"c_w_id\"; type=smallint; primary key }\n"
                           "  column { name=\"c_first\"; type=varchar(16) }\n"
                           "  column { name=\"c_middle\"; type=char(2) }\n"
                           "  column { name=\"c_last\"; type=varchar(16) }\n"
                           "  column { name=\"c_street_1\"; type=varchar(20) }\n"
                           "  column { name=\"c_street_2\"; type=varchar(20) }\n"
                           "  column { name=\"c_state\"; type=char(2); pool=&warehouse.w_state }\n"
                           "  column { name=\"c_zip\"; type=char(9); pool=&warehouse.w_zip }\n"
                           "  column { name=\"c_phone\"; type=char(16) }\n"
                           "  column { name=\"c_since\"; type=datetime }\n"
                           "  column { name=\"c_credit\"; type=char(2); pool=[\"GC\", \"BC\"] }\n"
                           "  column { name=\"c_credit_lim\"; type=float }\n"
                           "  column { name=\"c_discount\"; type=real }\n"
                           "  column { name=\"c_balance\"; type=float }\n"
                           "  column { name=\"c_ytd_payment\"; type=float }\n"
                           "  column { name=\"c_payment_cnt\"; type=smallint }\n"
                           "  column { name=\"c_delivery_cnt\"; type=smallint }\n"
                           "  column { name=\"c_data\"; type=varchar(500) }\n"
                           "\n"
                           "  foreign key c_w_id, c_d_id => district(d_w_id, d_id)\n"
                           "}\n";
